name: Lint

on: 
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.9'
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run eslint
  
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.9'
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run prettier